# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ChattingApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChattingApp
pod 'Firebase/Analytics' # Google Analytics

  target 'ChattingAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChattingAppUITests' do
    # Pods for testing
  end

end
